[base] Pull request #1629: Bugfix/python coverage build2
Merge in LINUXEP/everest-base from bugfix/python-coverage-build2 to develop

Squashed commit of the following:

commit efcf87c092f002e8d49e7cffb07bdf78e0b222d3
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Fri Jun 10 13:55:30 2022 +0100

    --ignore-installed is not a valid option on the pip/python version our test machines use.

commit 7bf5ed5b7dcb072f10fb62a26c8f901ffbe0f2f0
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Fri Jun 10 10:03:49 2022 +0100

    Disable extra debug from setup_build_tools.sh "#set -x"

commit 242ef2cfbdd268e6a260523a13a3a527b34223c9
Merge: a6c3829b3 46641edb0
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Fri Jun 10 09:59:17 2022 +0100

    Merge branch 'develop' of ssh://stash.sophos.net:7999/linuxep/everest-base into bugfix/python-coverage-build2

commit a6c3829b36a1d16b044cc10f4d8c69ca92790cf1
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Fri Jun 10 09:55:27 2022 +0100

    Pass in various python settings to registerCentral.in.sh and mcsrouter.in.sh via cmake so that we can run python coverage on any python 3.8 machine.

commit 478e86b16295566677ad3931b7b96346bd8a279f
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Wed Jun 8 16:51:27 2022 +0100

    Python coverage - Omit non-product python packages from coverage.

commit da33cea432ab265b62e3c6695d3addd29e559977
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Wed Jun 8 14:08:06 2022 +0100

    Python coverage - re-enable all tests.

commit 739977192b304899dd6d991131547ddf38101177
Merge: d1ee13c62 c0763ab93
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Tue Jun 7 16:47:26 2022 +0100

    Merge remote-tracking branch 'origin/bugfix/python-coverage-build2' into bugfix/python-coverage-build2

    # Conflicts:
    #	buildRunTestsAndProduceCoverageReport.sh

commit d1ee13c621819f16d76f317e5f158f60d4ca5384
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Tue Jun 7 16:46:08 2022 +0100

    Python Coverage - Previously sed was being used to replace paths in an sqlite DB file which is not a text file and therefore a bad idea. It was corrupting the .coverage file. In this commit, instead of the sed a simple script has been written to open the DB file properly and run an SQL update command over the "file" table. This utility can then be called from the coverage build and run bash script with the same replacements that it passed into sed.

commit c0763ab9371a4276ff3c965c5b85e9dc72668d60
Author: cas <casimir.overell@sophos.com>
Date:   Tue Jun 7 13:49:43 2022 +0100

    [TESTFIX] Attempting run with modified sed

commit 9170335a03eebf1b97907010c145b5f70d9779b0
Author: cas <casimir.overell@sophos.com>
Date:   Tue Jun 7 11:15:31 2022 +0100

    [TESTFIX] Letting it run to conclusion

commit cce4425df512061614209fb9bc330c9058d2b10d
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Mon May 30 12:14:45 2022 +0100

    Try and work out what is corrupting the python coverage file and just run one suite to speed things up while debugging

commit 8983663d26751c387a241d0939943806e50f30e4
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Tue May 24 07:50:57 2022 +0000

    Testing out not setting PYTHONHOME or LD_LIBRARY_PATH for python coverage builds.

commit a2d587eb17b0ac4861f78e940b251fcba1a938e7
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Mon May 23 12:13:24 2022 +0000

    testing out setting  PYTHONPATH to /usr/lib/python3.8/:\$BASE_DIR/lib64/ for python coverage mode builds

commit fd98b82d933bf2b49f214a717654d6f077a53c1b
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Thu May 19 16:46:56 2022 +0000

    try to use system python to run product when doing a coverage run.

commit 2c5a1a38bbe15ee967be34ba391cc6279c2717b1
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Thu May 19 15:26:43 2022 +0000

    Try python 3.8

commit 8ee5d0f5cc5570e1ef8328f60c809b6b9d93714a
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Thu May 19 14:47:31 2022 +0000

    Try to use system python to run product when doing a coverage run.

commit 6eec043d5b192e5be3f137b8f79b7619cf4e95c0
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Wed May 18 16:02:24 2022 +0000

    Add /usr/lib/python3.9/ to the python coverage path in the hope that it will be found and solve the following error. Also, sqlite is part of the standard library so cannot be pip installed.
    File "/opt/sophos-spl/base/lib64/python39.zip/sqlite3/dbapi2.py", line 27, in <module>
    ModuleNotFoundError: No module named '_sqlite3'

commit bfd06b8fbe1dad396f641a7863525e7852d0013c
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Wed May 18 14:53:38 2022 +0000

    Update JWT token to use a new token generated by CI. This one should stop tap fetch from trying to perform promote builds.

commit a20c633ed4acf8a3bd4a4b169f1e192df2193fd1
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Wed May 18 13:07:15 2022 +0000

    try using python 3.9 for coverage tests

commit 92f1652286777bd61d0169ff1af7e12a88bc8596
Author: Alex Cooper <alex.cooper@sophos.com>
Date:   Wed May 18 11:15:34 2022 +0000

    On the theory that MCS coverage tests are failing because product python needs coverage and that can be solved by having the system packages exposed to the product python in register central and mcsrouter.sh, so we're trying this.

... and 11 more commits