[base] [LINUXDAR-5431] Report logger.error for missing specs in get_version_of_component_with_tag_from_spec_xml_from_componentsuite
Causing test failures at:
https://sspljenkins.eng.sophos/job/UserTestJobs/job/DLCL-AWS-SystemProductTests-Parallel/label=CentosTemplate/47/robot/report/amazonlinux2022x64-log.html

 ${ExpectedBaseReleaseVersion} = WarehouseUtils . Get Version From Warehouse For Rigidname In Componentsuite ${BaseEdrAndMtrAndAVReleasePolicy}, ServerProtectionLinux-Base-component, ServerProtectionLinux-Base
Start / End / Elapsed:	20221026 16:22:20.839 / 20221026 16:22:20.841 / 00:00:00.002
16:22:20.839	TRACE	Arguments: [ '/opt/sspl/SupportFiles/CentralXml/RealWarehousePolicies/GeneratedAlcPolicies/base_edr_and_mtr_and_av_Release.xml' | 'ServerProtectionLinux-Base-component' | 'ServerProtectionLinux-Base' ]
16:22:20.839	DEBUG	Test timeout 10 minutes active. 540.493 seconds left.
16:22:20.840	DEBUG	get_version_of_component_with_tag_from_spec_xml_from_componentsuite: sdds.SSPL_MDR_1_0_13.2 -> {'importspec': <xml.etree.ElementTree.ElementTree object at 0x7fe527cc7e20>, 'publicationspec': <xml.etree.ElementTree.ElementTree object at 0x7fe527cc7460>}
16:22:20.840	DEBUG	Not got the spec for sdds.SSPL_1_2_1.1 from /opt/sspl/system-product-test-inputs/sdds-specs
16:22:20.840	FAIL	Did not find ServerProtectionLinux-Base-component in ['sdds.SSPL_MDR_1_0_13.2'] from ['sdds.CSP_LEGACY_155.3', 'sdds.CloudLin_SAV1063.1', 'sdds.WIN_MTR_2-3-0-68_2022-1.1', 'sdds.Cloud-SVE1373851.1', 'sdds.CSP_2-20-11_2022-2-2.1', 'sdds.SSPL_MDR_1_0_13.2', 'sdds.CSPCIX_2-0-24.28', 'sdds.SSPL_1_2_1.1']
16:22:20.841	DEBUG	Traceback (most recent call last):
  File "/opt/sspl/libs/WarehouseUtils.py", line 778, in get_version_from_warehouse_for_rigidname_in_componentsuite
    return get_version_of_component_with_tag_from_spec_xml_from_componentsuite(rigidname, componentsuite_rigidname,
  File "/opt/sspl/libs/WarehouseUtils.py", line 340, in get_version_of_component_with_tag_from_spec_xml_from_componentsuite
    raise AssertionError(f"Did not find {rigidname} in {examined} from {relevant_sdds_names}")
AssertionError: Did not find ServerProtectionLinux-Base-component in ['sdds.SSPL_MDR_1_0_13.2'] from ['sdds.CSP_LEGACY_155.3', 'sdds.CloudLin_SAV1063.1', 'sdds.WIN_MTR_2-3-0-68_2022-1.1', 'sdds.Cloud-SVE1373851.1', 'sdds.CSP_2-20-11_2022-2-2.1', 'sdds.SSPL_MDR_1_0_13.2', 'sdds.CSPCIX_2-0-24.28', 'sdds.SSPL_1_2_1.1']